Repository rustfoundation/safety-critical-rust-coding-guidelines, pull requests merged in 2025-08, with the labels that each got.

#162 [add tag] stack-overflow
  src/conf.py
Labels: enhancement

#170 Fix typo in conf.py
  src/conf.py
Labels: documentation

#132 [Guideline] Add do not divide by 0
  src/coding-guidelines/expressions.rst
Labels: decidability: undecidable, chapter: expressions

#184 Allow only a single selection for Category
  .github/ISSUE_TEMPLATE/CODING-GUIDELINE.yml
Labels: bug, ci/cd
